[package]
name = "rust-pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
fermium = "20022.0.0"
rand = "0.8.5"
ndarray = "0.15.6"